### ISSUE TITLE
Target nightly release and incorporate changes from firefox-nightly PKGBUILD.

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/pkgbuild-firefox-wayland-hg#1]
This makes much more sense than targeting release, and it'll probably prevent breakage in the future as features are disabled or enabled based on the nightly channel, which is based on a snapshot of the main branch of Firefox.

**Comment by thotypous** [comment]
Hi, thank you for your suggestion. Could you please make a pull request? I'm a little overwhelmed to work on anything now...

**Comment by nyabinary** [comment]
@thotypous ^

**Comment by nyabinary** [comment]
Done

**Comment by PedroHLC** [comment]
Reverted due to inconsistencies in #2 leading to AUR rejection.

**Comment by PedroHLC** [comment]
Closed with #3
